#!/usr/bin/env bash
# This file installs all dependencies needed to run core for tests

# Install dev env (including mongodb)
./scripts/setup-dev-env

# Install influxdb
./storages/engines/influxdb/scripts/setup

# Install graphicsmagick for preview functionality
sudo apt-get install graphicsmagick

#======================================================================
# If the script is run several times, this could fail because of occupied ports
# but in the isolated environment like docker it is ok, but for local machine
# installation could cause confusion

# Start influxdb and verify the status
sudo service influxdb start

# Start mongodb
IS_CI=true ./storages/engines/mongodb/scripts/start
