#!/bin/bash
set -e

# Sets up the dev environment on a MacOS or GNU/Linux system

# working dir fix
SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/.. # root

# setup git pre-commit hook if appropriate ($CI is "true" in GitHub workflows)
PRE_COMMIT="scripts/pre-commit"
if [[ -d .git && "$CI" != "true" ]]; then
  cp $PRE_COMMIT .git/hooks/
  echo ""
  echo "Git pre-commit hook setup from '$PRE_COMMIT'"
  echo ""
fi

# run additional Open-Pryv.io setup if appropriate
SCRIPT_EXTRAS="./scripts/setup-open"
if [[ -f $SCRIPT_EXTRAS ]]; then
  echo "Running Open-Pryv.io extra setup steps..."
  bash $SCRIPT_EXTRAS
fi

# create base file structure

VAR_PRYV_FOLDER=$SCRIPT_FOLDER/../var-pryv
mkdir -p $VAR_PRYV_FOLDER
export VAR_PRYV_FOLDER="$(unset CDPATH && cd "$VAR_PRYV_FOLDER" && pwd)"

export LOGS_FOLDER=$VAR_PRYV_FOLDER/logs
mkdir -p $LOGS_FOLDER

export ATTACHMENTS_FOLDER=$VAR_PRYV_FOLDER/attachments
mkdir -p $ATTACHMENTS_FOLDER

# database

. scripts/setup-mongodb
EXIT_CODE=$?
if [[ ${EXIT_CODE} -ne 0 ]]; then
  echo ""
  echo "Error setting up database; setup aborted"
  echo ""
  exit ${EXIT_CODE}
fi

echo ""
echo "Setup complete!"
echo ""
