#!/bin/bash
set -e

# Sets up MongoDB (engine and data) for server app(s)
# Meant to be run from dev env setup scripts

# Check OS and prepare download URL
# https://www.mongodb.com/try/download/community
if [ `uname` = "Linux" ]; then
  URLS=("https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-v6.0-latest.tgz"
  "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.7.0.tgz"
  "https://downloads.mongodb.com/compass/mongosh-1.8.2-linux-x64.tgz")
elif [ `uname` = "Darwin" ]; then # MacOS
  URLS=("https://fastdl.mongodb.org/osx/mongodb-macos-arm64-6.0.5.tgz"
  "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-macos-x86_64-100.7.0.zip"
  "https://downloads.mongodb.com/compass/mongosh-1.8.2-darwin-arm64.zip")
else
  echo "Installation is meant to be on Linux or MacOS"
  exit 1
fi

# working dir fix
SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/

# Check & create file structure

MONGO_FOLDER_NAME=mongodb-bin

if [[ -z "$VAR_PRYV_FOLDER" ]]; then
  echo ""
  echo "Error: Missing environment variable VAR_PRYV_FOLDER (root installation folder)"
  echo "(MongoDB will be installed (if needed) in 'VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME')"
  echo ""
  exit 1
fi

mkdir -p $VAR_PRYV_FOLDER

MONGO_DATA_FOLDER=$VAR_PRYV_FOLDER/mongodb-data
mkdir -p $MONGO_DATA_FOLDER

MONGO_LOGS_FOLDER=$VAR_PRYV_FOLDER/mongodb-logs
mkdir -p $MONGO_LOGS_FOLDER

echo ""
echo "Checking for MongoDB ($VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME)..."
if [[ ! -d $VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME ]]; then
  echo "...installing $MONGO_NAME"
  echo ""

  cd $VAR_PRYV_FOLDER
  mkdir -p $MONGO_FOLDER_NAME

  for URL in ${URLS[@]}; do
    FILEPATH="$(basename -- $URL)"
    echo "$FILEPATH $URL"
    curl -C - -o "$FILEPATH" $URL
    tar -xzf $FILEPATH -C $MONGO_FOLDER_NAME --strip-components 1
    rm -f $FILEPATH
  done

else
  echo "...already installed"
fi

echo ""
echo "Database setup complete."
echo ""
echo "To run MongoDB:"
echo "    ./scripts/start-mongo"
echo ""
