#!/bin/bash

SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/.. # root

set="abcdefghijklmonpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
n=20
rand="AUTO_GEN_"
DEFAULT_VALUE="REPLACE_ME"
for i in `seq 1 $n`; do
    char=${set:$RANDOM % ${#set}:1}
    rand+=$char
done
sed -i ".bak" "s/${DEFAULT_VALUE}/${rand}/g" "./configs/api.yml"
sed -i ".bak" "s/${DEFAULT_VALUE}/${rand}/g" "./configs/api-backloop.yml"

rm "./config.yml.bak"
rm "./configs/api-backloop.yml.bak"

echo "Set new random key for admin"

