#!/usr/bin/env bash
# This file installs all dependencies needed to run core for tests

# Install nats-server
./scripts/setup-nats-server

# Install dev env (including mongodb)
./scripts/setup-dev-env

# Install influxdb
./scripts/setup-influx

# Install graphicsmagick for preview functionality
sudo apt-get install graphicsmagick

#======================================================================
# If the script is run several times, this could fail because of occupied ports
# but in the isolated environment like docker it is ok, but for local machine
# installation could cause confusion

# Start nats-server
./nats-server/nats-server-v2.3.4-linux-amd64/nats-server &

# Start influxdb and verify the status
sudo service influxdb start

# Start mongodb
IS_CI=true ./scripts/start-mongo
