#!/bin/bash

SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER

bash ./setup-assets
bash ./setup-service-mail
bash ./setup-app-web-auth3
bash ./setup-admin-key
bash ./download-recla-certificates
